/* Generado por scripts/render-sfx.mjs a partir de @sts/core/sfx.js. No editar a mano. */
export const SFX_FILES = {
  "tap": require("../assets/sfx/tap.wav"),
  "on": require("../assets/sfx/on.wav"),
  "off": require("../assets/sfx/off.wav"),
  "badge": require("../assets/sfx/badge.wav"),
  "drip": require("../assets/sfx/drip.wav"),
  "slide": require("../assets/sfx/slide.wav"),
  "squeak": require("../assets/sfx/squeak.wav"),
  "scratch-soft": require("../assets/sfx/scratch-soft.wav"),
  "scratch-deep": require("../assets/sfx/scratch-deep.wav"),
  "scratch-wood": require("../assets/sfx/scratch-wood.wav"),
  "scratch-metal": require("../assets/sfx/scratch-metal.wav"),
  "scratch-glass": require("../assets/sfx/scratch-glass.wav"),
  "skin-rub": require("../assets/sfx/skin-rub.wav"),
  "skin-cut": require("../assets/sfx/skin-cut.wav"),
  "press": require("../assets/sfx/press.wav"),
  "pierce": require("../assets/sfx/pierce.wav"),
  "inject": require("../assets/sfx/inject.wav"),
  "pierce-solid": require("../assets/sfx/pierce-solid.wav"),
  "pierce-brittle": require("../assets/sfx/pierce-brittle.wav"),
  "breakthrough": require("../assets/sfx/breakthrough.wav"),
  "shatter": require("../assets/sfx/shatter.wav"),
  "snap": require("../assets/sfx/snap.wav"),
};
